Fixed with issue #4 i.e beautify the readme
SunitRoy2703/Tensorflow-lite-samples-kotlin pull request #14
Opened 2022-02-05 04:34 UTC by Bhawna1203

2022-02-06 05:59 UTC, SunitRoy2703 requested changes
Awesome @Bhawna1203, let me know when you're done with the changes

2022-02-06 05:59 UTC, SunitRoy2703 commented on README.md
> +## Recommedation :ghost:
Can you change ghost emoji to 💬

2022-02-06 05:59 UTC, SunitRoy2703 commented on README.md
> + #### :wave: Contributions are welcome, checkout [contribution guidelines](./CONTRIBUTING.md) :memo:
Don't use more than 3 # it makes the text really small

2022-02-07 04:04 UTC, Bhawna1203 commented on README.md
> + #### :wave: Contributions are welcome, checkout [contribution guidelines](./CONTRIBUTING.md) :memo:
okkk

2022-02-07 04:20 UTC, Bhawna1203 commented on README.md
> +## Recommedation :ghost:
done with this part

2022-02-07 06:56 UTC, SunitRoy2703 commented
@Bhawna1203 Great work, I'm merging it!

2022-02-07 06:56 UTC, merged